version: '3.4'
services:
  route_handler:
    restart: always
    build:
      target: prod
    ports:
      - '80:80'
    volumes:
      - ./php:/www/data
  client:
    restart: always
    build:
      target: prod
  php:
    restart: always
    volumes:
      - ./php:/www/data
  database:
    restart: always
    volumes:
      - './database:/docker-entrypoint-initdb.d'
