version: '3.4'
services:
  route_handler:
    build:
      target: prod
    ports:
      - '80:80'
    volumes:
      - ./php:/www/data
  client:
    build:
      target: prod
  php:
    volumes:
      - ./php:/www/data
  database:
    volumes:
      - './database:/docker-entrypoint-initdb.d'
