version: '3.4'
services:
  route_handler:
    restart: always
    build:
      context: ./route_handler
    depends_on:
      - client
      - php
  client:
    stdin_open: true
    restart: always
    build:
      context: ./client
  php:
    restart: always
    build:
      context: ./php
  database:
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'example'
      MYSQL_DATABASE: 'geo_search'
      MYSQL_USER: 'james'
      MYSQL_PASSWORD: 'secret'