version: '3.4'
services:
  route_handler:
    build:
      target: dev
    ports:
      - '3050:80'
    volumes:
      - ./php:/www/data
  client:
    build:
      target: dev
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    build:
      target: dev
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - '4000:4000'
  php:
    volumes:
      - ./php:/www/data
    ports:
      - '9000:9000'
  database:
    volumes:
      - './database:/docker-entrypoint-initdb.d'
    ports:
      - '3051:3306'