version: '3.4'
services:
  route_handler:
    build:
      context: ./route_handler
      dockerfile: Dockerfile
    depends_on:
      - client
      - api
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
  database:
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'example'
      MYSQL_DATABASE: 'geo_search'
      MYSQL_USER: 'james'
      MYSQL_PASSWORD: 'secret'