version: '3'
services:
  client:
    restart: always
    build:
      context: ./client
    depends_on:
      - php
  database:
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'example'
      MYSQL_DATABASE: 'geo_search'
      MYSQL_USER: 'james'
      MYSQL_PASSWORD: 'secret'