version: '3.4'
services:
  route_handler:
    restart: always
    build:
      target: prod
    ports:
      - '80:80'
  client:
    restart: always
    build:
      target: prod
  api:
    build:
      target: prod
  database:
    restart: always
    volumes:
      - './database:/docker-entrypoint-initdb.d'
