version: '3'
services:
  route_handler:
    restart: always
    build:
      context: ./route_handler
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
    volumes:
      - ./php:/www/data
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  php:
    build:
      context: ./php
      dockerfile: Dockerfile.dev
    volumes:
      - ./php:/www/data
    ports:
      - '9000:9000'
  database:
    volumes:
      - './database:/docker-entrypoint-initdb.d'
    ports:
      - '3051:3306'