export const CHANGE_RANGE = "CHANGE_RANGE";
export const CHANGE_LONGITUDE = "CHANGE_LONGITUDE";
export const CHANGE_LATITUDE = "CHANGE_LATITUDE";
export const SEARCH_AT_POINT = "SEARCH_AT_POINT";
export const UPDATE_RESULTS = "UPDATE_RESULTS";
export const SELECT_SPECIES = "SELECT_SPECIES";
export const SHOW_SPECIES_RANGE = "SHOW_SPECIES_RANGE";
export const HIDE_SPECIES_RANGE = "HIDE_SPECIES_RANGE";
