export const CHANGE_RANGE = "CHANGE_RANGE";
export const SEARCH_AT_POINT = "SEARCH_AT_POINT";
export const UPDATE_RESULTS = "UPDATE_RESULTS";
export const SELECT_SPECIES = "SELECT_SPECIES";
export const SHOW_SPECIES_RANGE = "SHOW_SPECIES_RANGE";
